### ISSUE TITLE
redirect/proxying call should use .content instead of .text

### ISSUE THREAD

**Issue by TimLChan** [soju6jan/klive#1]
The line below in the redirect route will decode the video fragment into text (which then can't be played), when it should be returned back as content instead.

https://github.com/soju6jan/klive/blob/5b9402cbf153cb86ee5fab54c2921db5024ca217/plugin.py#L313

^ Should revert the change from `res.text` back to `res.content`

**Comment by soju6jan** [comment]
thanks
