### ISSUE TITLE
klive 서버 운용에 필요한 지식 문의드립니다. 

### ISSUE THREAD

**Issue by taxdriver4u** [soju6jan/KLive#1]
시놀리지 나스 713+를 사용하고 있습니다.
나스에 klive 서버를 올리고 싶은데, 지식이 마니 필요한 부분인지요? 웹서버를 만들어 본 경혐은 없습니다.
python2.7이 먼지도 모르는 상태입니다.

kliveserver폴더를 복사에서 나스 웹폴더에 복사해봤는데 해당 주소로 접속해도 접속이 안되서 어디서 부터 시작해야 할지 잘 몰라서 문의드려봅니다.

**Comment by soju6jan** [comment]
https://soju6jan.github.io/klive/2018/10/14/klive_install/
보면서 설치해보시고 구체적으로 안되는 부분을 알려주세요.

**Comment by taxdriver4u** [comment]
매번 귀찮고 번거롭고 수준 낮은 질문 드려서 죄송합니다.

https://soju6jan.github.io/klive/2018/10/14/klive_install/ 주로 접속해서 순서대로 하다가 막혀서 질문드립니다.

시놀리지nas 713+ 사용중입니다. (구글링해보니 python 2.7 기본으로 구동된다고 되어 있습니다.)

1. Putty로 nas에 접속후 admin계정으로 로그인 했습니다.

2. 소스다운로드
   가. git clone 명령어가 발견되지 않는다는 오류 메세지가 떠서 구글링 한 다음 'git server' 패키지를 설치한 후 
       1) git clone https://github.com/soju6jan/Klive.git 입력해서 잘 설치되었습니다.
   
   나.  lib 폴더 복사
         cd Klive/ >오류 메세지 안뜸
         mv lib/ klive_server/ >오류 메세지 안뜸
         cd klive_server/ >오류 메세지 안뜸

 
3. python 세팅
   가. pip 설치
       ' sudo; apt: command not found'라고 오류 메세지가 뜸니다.
       ' sudo'만 입력하면 옵션들에 대한 설명이 뜨고
        'apt'만 입력하면 apt: command not found라고 뜨네요

질문? 다른 패키지를 설치해야 하는건지 구글링으로 해결을 못하겠습니다. 어찌해야 할지

**Comment by taxdriver4u** [comment]
제가 푹(유료), 티빙(유료), 옥수수(skt정액고객)인데, 올레tv를 사용하지 않아서
채널 목록을 푹, 티빙, 옥수수 위주로 바꾸고 싶은데 어디를 수정해야 할른지요

**Comment by taxdriver4u** [comment]
어찌어찌 라이브채널에서 방송이 나오는것 까지는 했네요. 대박 신기하네요.
다만, 서비스 등록 설정이 안되서 매번 터미널 열고 실행을 해주고 있습니다.

시놀로지 nas에서는 systemclt명령이 없다고 메세지가 나오는데
구글링으로 방법을 못찾고 있는 상태입니다.
방법이 있다면 도움 요청드려 봅니다.
매번 번거롭게 해드리는점 죄송하고 감사드린다는 말씀 전합니다.

**Comment by taxdriver4u** [comment]
추가로 Klive_server가 더욱 발전된 프로그램이 되길 바라는 마음에 아래 기능 같은게 추가되면 좋을거 같습니다.

1. 멀티뷰기능(cJ뷰잉이나 u+tv에서 사용되는걸 봤습니다.
2. 채널수가 100개가 넘다보니 채널을 찾아서 전환하는데  번거로운 점이 있는거 같습니다. 채널을 카타고리(지상파, 뉴스, 스포츠, 어린이, 증권경제 등)로 분류하면 좋을거 같습니다. (cj뷰잉에서 제공되는 기능)

**Comment by taxdriver4u** [comment]
저도 nas재부팅할 일이 없어서 'python kliveProxy.py &'으로 하면 될거 같습니다. 감사합니다. ^^

외부 접속시 푹 라이브채널 재생과 관련해서, 외부에서 klive어플을 통해 라이브채널에서 티빙이나 옥수수 라이브 채널은 정상적으로 잘 재생되는데, 푹 관련 라이브채널만  재생이 안되네요.  말씀대로라면 다같이 안되거나 다같이 되거나 해야 될거 같은데 말입니다.  앱개발에 참고하시라 알려드립니다.
