### ISSUE TITLE
Plex plugin에서 pooq 사용시

### ISSUE THREAD

**Issue by unicode45** [soju6jan/KLive#12]
훌륭한 S/W 제공해주셔서 감사합니다.

동일 계정 설정으로 klive server 및 KODI 상에서는 동작이 문제 없습니다만, 유독 plex 플러그인 중 pooq의 경우, 채널 목록도 나옵니다만, 채널 재생시 
"재생 오류
변환에 실패했습니다. 트랜스 코더를 시작하지 못했습니다."
라는 에러 메세지가 뜨면서 재생이 되지 않습니다.

**Comment by soju6jan** [comment]
원인파악했고 수정예정입니다.
