### ISSUE TITLE
klive init.d 스크립트 관련 개선방안

### ISSUE THREAD

**Issue by DoJungJin** [soju6jan/KLive#15]
소주6잔님 감사합니다. 깃허브 짬이 얼마 없어서 이슈로 남깁니다. 좋은 하루 되세요 ㅎㅎ

**Comment by DoJungJin** [comment]
https://github.com/djjproject/android_over_linux/blob/master/init.d/klive

**Comment by soju6jan** [comment]
잠자님 감사합니다~ 포함시켜 놓을께요
