### ISSUE TITLE
epg 2일치 이상 받아오는 방법 문의

### ISSUE THREAD

**Issue by ohnggni** [soju6jan/KLive#20]
안녕하세요? docker-klive를 설치하여 docker-tvheadend에서 사용하고 있습니다.
현재 주력으로 olleh 모바일 TV만 쓰고 있는데, EPG 관련 두가지 질문이 있습니다.
1) EPG를 2일치 이상 끌어올 수 있는 방법이 있는지요?
2) 터미널에서 EPG 재생성하는 방법이 있는지요?
  - 도커 이미지 진입해서 python klive.py epg 명령을 쓰니 아래와 같은 에러가 발생해서 그렇습니다.

root@klive:/klive_server/output$ python /klive_server/klive.py epg
Traceback (most recent call last):
  File "/klive_server/klive.py", line 8, in <module>
    from pooq import *
ImportError: No module named pooq

**Comment by ohnggni** [comment]
우선 o****모바일의 경우 klive.xml에서 2일치 이상을 가져올 방법은 없는 것으로 보입니다. 사실 그게 필요했던 이유는 p***y채널들의 경우 epg2xml쪽에서 가져올 방법이 없었기 때문이었습니다.

그리고 터미널에서 epg 재생성 명령의 경우,
klive.py 일부 수정이 필요한데,
"klive.py", line 298, in main
    ret = MakeEPG(sys.argv[2]) 를 ret = MakeEPG(sys.argv[1])로 바꾸었더니,
klive.py epg 명령이 이상없이 잘 실행되는 것을 확인 했습니다. 물론 실행 위치는 klive_server 폴더에서
실행해야 하더군요. 

epg의 경우 4시간(?)마다 자동 생성되는 것으로 보이나, 이런 저런 사정으로 굳이
정해진 시간에 딱 생성하고 싶어서 시놀로지 작업 스케줄러를 이용해서 아래와 같은 명령어가
자동실행되게 하였습니다. 
docker exec -i klive /bin/bash -c "cd /klive_server && python klive.py epg" &

혹시라도 저와 같은 의도로 작업하시는 분들이 있을 것 같아, 댓글 남겨 놓습니다.
좋은 하루 되세요.

**Comment by taxdriver4u** [comment]
klive앱 대신 TVirl을 쓸 경우, 라이브채널에서 채널을 카타고리(영화, 뮤직, 뉴스등)으로 분류할 수 있는 이유로 TVirl을 쓰보려고 합니다.
그런데 TVirl에서 Klive앱에서 사용하는 http://로컬주소:9801/epg를 적용해보 epg가 입혀지지 않습니다.
klive_serve의 output폴더 안 klive_costom.xml 파일을 적용하면 epg가 잘 입혀집니다.
다만,   klive_costom.xml 파일을 매번 복사해와서 수동으로 epg를 적용해야 합니다. 
 klive_costom.xml 파일을 url로 적용할 방법은 없을까요?

**Comment by kims602** [comment]
> klive앱 대신 TVirl을 쓸 경우, 라이브채널에서 채널을 카타고리(영화, 뮤직, 뉴스등)으로 분류할 수 있는 이유로 TVirl을 쓰보려고 합니다.
> 그런데 TVirl에서 Klive앱에서 사용하는 [http://로컬주소:9801/epg를](http://%EB%A1%9C%EC%BB%AC%EC%A3%BC%EC%86%8C:9801/epg%EB%A5%BC) 적용해보 epg가 입혀지지 않습니다.
> klive_serve의 output폴더 안 klive_costom.xml 파일을 적용하면 epg가 잘 입혀집니다.
> 다만, klive_costom.xml 파일을 매번 복사해와서 수동으로 epg를 적용해야 합니다.
> klive_costom.xml 파일을 url로 적용할 방법은 없을까요?

방법이 있습니다.

klive.py에서 69번째 줄에 current_path = 내용을 기존내용에서 "/volume1/web/~~~로 설정하시면 됩니다.

**Comment by wjdgks1224** [comment]
flask 서버에서 형식을 text로 반환해서 그런것일수도 있습니다. @route('/epg') 아래의 함수에서 `return Response(res, mimetype='text/xml')`으로 하면 될 수 있습니다. 감사합니다!

**Comment by taxdriver4u** [comment]
kims602님 
web아래 klive폴더를 생성한 후, klive.py에서 69번째 줄에 current_path = 내용을 기존내용에서 /volume1/web/klive 설정한 후 실행하였더니 아래와 같이 오류 메세지가 나옵니다.
![20190222_221307](https://user-images.githubusercontent.com/44728502/53245268-9a486f00-36f0-11e9-9728-44e94847313e.jpg)

**Comment by taxdriver4u** [comment]
wjdgks1224님, 답변감사드립니다
@route('/epg') 아래의 함수에서 `return Response(res, mimetype='text/xml')`
어느 파일에 포함되어 있는지요?

**Comment by taxdriver4u** [comment]
> flask 서버에서 형식을 text로 반환해서 그런것일수도 있습니다. @route('/epg') 아래의 함수에서 `return Response(res, mimetype='text/xml')`으로 하면 될 수 있습니다. 감사합니다!

wjdgks1224님, 답변감사드립니다
@route('/epg') 아래의 함수에서 `return Response(res, mimetype='text/xml')`
어느 파일에 포함되어 있는지요?

**Comment by taxdriver4u** [comment]
> > klive앱 대신 TVirl을 쓸 경우, 라이브채널에서 채널을 카타고리(영화, 뮤직, 뉴스등)으로 분류할 수 있는 이유로 TVirl을 쓰보려고 합니다.
> > 그런데 TVirl에서 Klive앱에서 사용하는 [http://로컬주소:9801/epg를](http://%EB%A1%9C%EC%BB%AC%EC%A3%BC%EC%86%8C:9801/epg%EB%A5%BC) 적용해보 epg가 입혀지지 않습니다.
> > klive_serve의 output폴더 안 klive_costom.xml 파일을 적용하면 epg가 잘 입혀집니다.
> > 다만, klive_costom.xml 파일을 매번 복사해와서 수동으로 epg를 적용해야 합니다.
> > klive_costom.xml 파일을 url로 적용할 방법은 없을까요?
> 
> 방법이 있습니다.
> 
> klive.py에서 69번째 줄에 current_path = 내용을 기존내용에서 "/volume1/web/~~~로 설정하시면 됩니다.

kims602님
web아래 klive폴더를 생성한 후, klive.py에서 69번째 줄에 current_path = 내용을 기존내용에서 /volume1/web/klive 설정한 후 실행하였더니 아래와 같이 오류 메세지가 나옵니다.
![20190222_221307](https://user-images.githubusercontent.com/44728502/53245268-9a486f00-36f0-11e9-9728-44e94847313e.jpg)

**Comment by kims602** [comment]
> > > klive앱 대신 TVirl을 쓸 경우, 라이브채널에서 채널을 카타고리(영화, 뮤직, 뉴스등)으로 분류할 수 있는 이유로 TVirl을 쓰보려고 합니다.
> > > 그런데 TVirl에서 Klive앱에서 사용하는 [http://로컬주소:9801/epg를](http://%EB%A1%9C%EC%BB%AC%EC%A3%BC%EC%86%8C:9801/epg%EB%A5%BC) 적용해보 epg가 입혀지지 않습니다.
> > > klive_serve의 output폴더 안 klive_costom.xml 파일을 적용하면 epg가 잘 입혀집니다.
> > > 다만, klive_costom.xml 파일을 매번 복사해와서 수동으로 epg를 적용해야 합니다.
> > > klive_costom.xml 파일을 url로 적용할 방법은 없을까요?
> > 
> > 
> > 방법이 있습니다.
> > klive.py에서 69번째 줄에 current_path = 내용을 기존내용에서 "/volume1/web/~~~로 설정하시면 됩니다.
> 
> kims602님
> web아래 klive폴더를 생성한 후, klive.py에서 69번째 줄에 current_path = 내용을 기존내용에서 /volume1/web/klive 설정한 후 실행하였더니 아래와 같이 오류 메세지가 나옵니다.
> ![20190222_221307](https://user-images.githubusercontent.com/44728502/53245268-9a486f00-36f0-11e9-9728-44e94847313e.jpg)

current_path = "/volume1/web/klive"  << ""를 하시면

/volume1/web/klive/output/klive_costom.xml이 생기게 되고

http://localhost/klive/output/klive_costom.xml 으로 넣으시면 됩니다

**Comment by wjdgks1224** [comment]
제가 제시한 방법은 틀린것같지만 그래도 코멘트 남겨봅니다.. `@app.route('/epg')`는 kliveProxy의 32줄쯤에 있을겁니다. 직접 파일을 넣으면 되지만 URI로 접근해서 안되는 이유는 TVIrl측이 주소를 XML이 아닌 텍스트로 이해해서 그럴거라고 해석했는데 @kims602 님은 좀 다르신가봅니다..

**Comment by taxdriver4u** [comment]
> 제가 제시한 방법은 틀린것같지만 그래도 코멘트 남겨봅니다.. `@app.route('/epg')`는 kliveProxy의 32줄쯤에 있을겁니다. 직접 파일을 넣으면 되지만 URI로 접근해서 안되는 이유는 TVIrl측이 주소를 XML이 아닌 텍스트로 이해해서 그럴거라고 해석했는데 @kims602 님은 좀 다르신가봅니다..

조금 다른 질문입니다.
klive서버에서 구글음성인식을 이용한 채널전환을 가능하게 하고자 합니다. 
가령 'ok, google, mbn틀어줘'

cj뷰잉에서 라이브채널에서  epg, 카타고리에 따른 채널 분류, 음성으로 채널전환이 정상적으로 구동됩니다.

TVirl에서 채널리스만 적용할 경우, 음성으로 채널전환이 정상적으로 구동됩니다.
그런데 epg를 입히게 되면, 채널은 영화, 음악 등 정상적으로 분류되는 반면 음성으로 채널전환이 적용되지 않습니다.
https://cafe.naver.com/shieldtv/261
epg가 적용되면 채널네임이 바뀌는 건지요?
