### ISSUE TITLE
올레티비 모바일... 뭔가 올레쪽에서 수정을 한것 같습니다.

### ISSUE THREAD

**Issue by rubyon** [soju6jan/KLive#25]
오늘 EPG 가 업데이트 되어 있지 않길래 뭐지 하고 봤더니...

KLive 실행할때 오류가 나는군요...

뭔가 KT 쪽에서 액션을 취한거 같은데...

**Comment by wjdgks1224** [comment]
저도 urllib2측에서 request를 날릴때 에러가 납니다... 별도로 POSTMAN이라는 프로그램으로 테스트 해봐도 결과가 제대로 나오지 않네요!

**Comment by soju6jan** [comment]
수정했습니다.
